language: php

php:
  - '7.1'

env:
  - SYMFONY_VERSION="4.2.*"

## on test juste sur les branch dev et master
branches:
  only:
    - master
    - develop
    - deploymentTest
    - deployment

before-install:
  - composer self-update

install:
  - composer install

script:
  - php vendor/bin/phpunit

jobs:
  include:
    - stage: build docker image
    script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t projectmaster .
      - docker images
      - docker tag projectmaster $DOCKER_USERNAME/projectmaster
      - docker push $DOCKER_USERNAME/projectmaster
