language: php
sudo: required
services:
- docker
php:
- '7.1'
env:
  matrix:
  - SYMFONY_VERSION="4.2.*"
branches:
  only:
  - master
  - develop
install:
- composer self-update
- composer install
script:
- php vendor/bin/phpunit
#deploy:
#  provider: gae
#  keyfile: gce.json
#  project: project-tvshow
#  skip_cleanup: true
#  on:
#    branch: master
#before_install:
#- openssl aes-256-cbc -K $encrypted_c51c3e5f5d01_key -iv $encrypted_c51c3e5f5d01_iv
#  -in gce.json.enc -out gce.json -d
