language: php
php:
  - '7.1'
services:
- docker


env:
  matrix:
    - SYMFONY_VERSION="4.2.*"
#  global:
#    - secure: kXC0MeE7HchxNlc5rc+j+EZdcV2hQO+bINlgfEEKwpDnyQIsTqwTYsrvmZQkYYLeOSOh07HXsv93irXNihYVZ7F0KdRxtfX2HEhWlNPDfcdhTROOoBI/vsenisJMZxRdLRIRZqjwazg0A2WFhRRF918i2reJ8HmOiKtiWCskfU1oRpHoYHU2OQZLe9XN4+ZWVZUbw2EwRC1mkYorsd2OolMG5pVfAb/SLV/FecZdnqVE8tTvdzdzI0GtbxLcpHpQuR6zRzTahAiuFlyn9LaptdZYR8nZ2Pxskrj/OVfq8b1P3oQIp2xc4hPmRSxnaD4Vkwe92uvGDPQdJM4XXVio8JHh0qIVun9x5lFdF/yY4euxGIMLrruxx2mw3/iCXPYwsCtmlcpOIt9noV38tQfzxU9+BWJnHjrnEcuBYopPUwdeAYfQqzgWyf2qBNqv3qJ0TIGdYcujr+r7h3esOLYdld7BL1mNb0ZYp5l1f7zgYFXqGZJ/oWz1C0K8d9FtjO6agLdGCZSTAVdd4L9qvOm4kCUSYZ/E1EUBvSKezO5sEJ98xsZI6kiILfHi5M3t6NJFl7lD3fdCB6H96VTbZ7lxjbWPkyfosHU3BDHTyi37IaGouN745jAkRqfb24+c+SqXnwyhStP7Gsfvk5UWHtog1eAj0dGCopQe9BJd+6tgjAk=
#    - secure: lbtL8XdAcDWTNG5rBSAEYsBcRkwHcOEAtuXDd1c56RlRFrx3UGXHxh4zEDhVFwjbZAer0/jzCEe/6Gmlc0S56wJEdOj4C0YjdiNWdX13evP9PTez6vBfV20yDhz8+rpors/8iO9r3sYxufpsbAKDDXQrlp40/5BUQqNHI6kAPZC5N3cCbJRmnwMzFAn9ccGRX83rIcs1NiBNzQboawkXoaCzQT3voP0FS3IkuMODR+uRThlq3sP8LwrX1d2AZZmwuqqUSUN5WcVBj8uWdNb1cM5G7UCbvRHNXAu9++LfpVhHHSWNW8yoY2XBe/TMlw4/TdvjgPMkLp1mK0flmGfEPiQPjtYshoT1Diu744iR1SKKcpI9dKPww8YEPM2DPPRxwj/GSBoX2qGM1U7UeZACUYK8u7GSM3r2h2IiC6RMBuozTRWtfdhSNhXKtGix7lINQYnIsxUJYRtQx8dRdDvYh+kjCD32U633RoEczL+zfUXn1STY83diuPWracQEp5GUk4I6hCeNQj4bXU6N/qfIUlzQe4s+JFne484AEDYzRSVJpvsNj9UzdQTYomvTQcOG0ASYGCRznLoFSYcdD4Zr7mIhV8vIBBuIw7dq/MJCoLl3S+/QL8GT1gT46UK7amrWIDBHUM20xXUSycf4iUEpj//fkSoHS87O/7O3xeREahU=


## on test juste sur les branch dev et master
branches:
  only:
    - master
    - develop
    - deploymentTest

before-install:
- composer self-update

install:
- composer install

script:
- php vendor/bin/phpunit

jobs:
  include:
    - stage: build docker image
     script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t projectmaster .
        - docker images
        - docker tag projectmaster $DOCKER_USERNAME/projectmaster
        - docker push $DOCKER_USERNAME/projectmaster
