language: php

services:
- docker

php:
- '7.1'
env:
  - SYMFONY_VERSION="4.2.*"
 branches:
  only:
  - master
  - develop
before-install:
- composer self-update
install:
- composer install
script:
- php vendor/bin/phpunit
before_deploy:
- docker build -t johannrmd/projectmaster .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push johannrmd/projectMaster
