version: '3'

services:
  web:
    image: nginx:latest
    volumes:
      - ./../backend:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - code-network

  php:
    build:
      context: .
      dockerfile: ./docker/php/DockerFile
    restart: always
    expose:
      - '9000'
    volumes:
      - ./../backend:/var/www/html
    networks:
      - code-network

  mysql:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD:  root
    networks:
      - code-network


networks:
  code-network:
    driver: bridge